/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class spotify_Session */

#ifndef _Included_spotify_Session
#define _Included_spotify_Session
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: instance */
/*
 * Class:     spotify_Session
 * Method:    Init
 * Signature: (Lspotify/SessionListener;)V
 */
JNIEXPORT void JNICALL Java_spotify_Session_Init
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     spotify_Session
 * Method:    Login
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_spotify_Session_Login
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     spotify_Session
 * Method:    Search
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_spotify_Session_Search
  (JNIEnv *, jobject, jstring, jint, jint, jint, jobject);

/*
 * Class:     spotify_Session
 * Method:    Play
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_spotify_Session_Play
  (JNIEnv *, jobject, jstring);

/*
 * Class:     spotify_Session
 * Method:    RegisterPlayer
 * Signature: (Lspotify/Player;)V
 */
JNIEXPORT void JNICALL Java_spotify_Session_RegisterPlayer
  (JNIEnv *, jobject, jobject);

/*
 * Class:     spotify_Session
 * Method:    ReadArtistImage
 * Signature: (Ljava/lang/String;Lspotify/Image;)V
 */
JNIEXPORT void JNICALL Java_spotify_Session_ReadArtistImage
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     spotify_Session
 * Method:    ReadAlbumImage
 * Signature: (Ljava/lang/String;Lspotify/Image;)V
 */
JNIEXPORT void JNICALL Java_spotify_Session_ReadAlbumImage
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
